import { CertInfo } from "../CertificationStore";
import TTTServer from "../TTTServer";
declare class AdminServer {
    private readonly _server;
    private _port;
    private _tttServer;
    constructor(tttServer: TTTServer, tls: boolean, certInfo?: CertInfo);
    private route;
    private routeDelete;
    private routePost;
    private routeGet;
    private onGetWebResource;
    private onUpdateAdminCert;
    private static getSessionKey;
    private onUpdateServerOption;
    private onUpdateTunnelingOption;
    private onRemoveTunnelingOption;
    private onGetValidateSession;
    private checkSession;
    private onGetAdminCert;
    private getNumberInPath;
    private onActiveTunneling;
    private onDeleteExternalServerCert;
    private onUpdateExternalServerCert;
    private onGetVersion;
    private onGetExternalServerCert;
    private onGetClientSysInfo;
    private getQueryParam;
    private onGetEmptyKey;
    private onLogin;
    private static readJson;
    private validateSession;
    private onGetServerOption;
    private onGetSysInfo;
    private onGetSysUsage;
    private onGetClientStatus;
    private onGetTunnelingOption;
    private onGetExternalServerStatuses;
    private onGetServerOptionHash;
    listen(port: number): Promise<number>;
    close(): Promise<boolean>;
    private contentTypeFromExt;
}
export default AdminServer;
